### ISSUE TITLE
TLS negotiation failure with rustls against ES 7.1.0

### ISSUE THREAD

**Issue by dcarosone** [elastic-rs/elastic#362]
I'm using 0.21.pre4 against ES 7.1.0.  TLS negotiation fails with 'no cipher suites in common'.

Looking at docs, the default cipher set for Java/elastic, even with the 'stronger' crypto modules enabled, don't include any GCM modes, mostly various bit-lengths of AES CBC modes. Meanwhile, rustls only includes ciphers with PFS, so there's nothing in common.  Notionally I can add those to ES by editing config and digging through ES and Oracle doc links to find magic strings.

But the net result is that the elastic crate in default config won't talk to elasticsearch in default config with TLS, and that's probably not desirable as much as we'd prefer to have stronger ciphers used.

Workaround is instead to pull in `reqwest` directly in my own `Cargo.toml` to add back the default feature, so it links against `native-tls` (openssl) again.

Related to #341 and #336

**Comment by KodrAus** [comment]
Thanks for the report @dcarosone 

This is unfortunate. I think we could look at mirroring `reqwest`'s TLS features, so you opt-in to either `openssl` or `rustls`:

```toml
[dependencies.reqwest]
default-features = false

[features]
rustls-tls = [
    "reqwest/rustls-tls"
]

default-tls = [
    "reqwest/default-tls"
]
```

That way you could pick the implementation to use.

What do you think?
